openapi: '3.0.0'
info:
  title: PayID
  version: '0.0.1'
paths:
  /invoice:
    get:
      summary: get-invoice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xrpl-devnet+json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
            application/xrpl-mainnet+json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
            application/xrpl-testnet+json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
        '404':
          description: Not Found
        '503':
          description: Service Unavailable
      operationId: get-path-invoice
      parameters:
        - schema:
            # Typed as a string to get around swagger-codegen issues.
            # TODO(keefertaylor): Fix after https://github.com/swagger-api/swagger-codegen/issues/10105 is resolved
            type: string
          in: query
          name: nonce
          description: ''
          required: true
    post:
      summary: post-invoice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
            application/xrpl-mainnet+json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
            application/xrpl-testnet+json:
              schema:
                $ref: '#/components/schemas/SignatureWrapper_Invoice'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '413':
          description: Request Entity Too Large
        '422':
          description: Unprocessable Entity
        '451':
          description: Unavailable due to legal reasons
        '503':
          description: Service Unavailable
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureWrapper_Compliance'
      operationId: post-path-invoice
      parameters:
        - schema:
            # Typed as a string to get around swagger-codegen issues.
            # TODO(keefertaylor): Fix after https://github.com/swagger-api/swagger-codegen/issues/10105 is resolved
            type: string
          in: query
          name: nonce
          description: ''
          required: true